In [1]:
import torch
print(torch.__version__) 

2.7.0+cpu


<p style="font-family:ComicSansMS; font-size: 30px; color: magenta"> 2.1. Data Manipulation</p>

<p style="font-family:ComicSansMS; font-size: 24px; color: orange"> 2.1.1. Getting Started</p>

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
# We can inspect the total number of elements in a tensor via its numel method.
x.numel()

12

In [5]:
# We can access a tensor’s shape (the length along each axis) by inspecting its shape attribute.
x.shape

torch.Size([12])

In [6]:
# We can change the shape of a tensor without altering its size or values, by invoking reshape.
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
# To automatically infer one component of the shape, we can place a -1 for the shape component 
# that should be inferred automatically
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
X = x.reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
#  We can construct a tensor with all elements set to 0 and a shape of (2, 3, 4) via the zeros function.
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
# Similarly, we can create a tensor with all 1s by invoking ones.
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
# The following snippet creates a tensor with elements drawn 
#     from a standard Gaussian (normal) distribution 
#         with mean 0 and standard deviation 1.
torch.randn(3, 4)

tensor([[-0.5284, -1.8388, -1.2645,  0.0815],
        [ 0.4971, -0.0296, -0.7228,  0.7524],
        [-0.7695,  1.1021, -0.8682, -0.8941]])

In [13]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

<p style="font-family:ComicSansMS; font-size: 24px; color: orange"> 2.1.2. Indexing and Slicing</p>

In [15]:
# Finally, we can access whole ranges of indices via slicing (e.g., X[start:stop]), 
#     where the returned value 
#         includes the first index (start) but not the last (stop).
X[-1], X[1:3]
# To access an element based on its position relative to the end of the list, we can use negative indexing

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [16]:
# Beyond reading them, we can also write elements of a matrix by specifying indices.
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
# For instance, [:2, :] accesses the first and second rows, 
#   where : takes all the elements along axis 1 (column)
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

<p style="font-family:ComicSansMS; font-size: 24px; color: orange"> 2.1.3. Operations¶</p>

In [19]:
# Most standard operators, including unary ones like, can be applied elementwise.
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [20]:
# The common standard arithmetic operators 
#   for addition (+), subtraction (-), multiplication (*), division (/), and exponentiation (**) 
#       have all been lifted to elementwise operations for identically-shaped tensors of arbitrary shape.
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [21]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# he example below shows what happens when 
#     we concatenate two matrices along rows (axis 0) 
#         instead of columns (axis 1)
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [23]:
# Sometimes, we want to construct a binary tensor via logical statements. 
# Take X == Y as an example. For each position i, j, if X[i, j] and Y[i, j] are equal, 
#       then the corresponding entry in the result takes value 1, 
#               otherwise it takes value 0.
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [24]:
# Summing all the elements in the tensor yields a tensor with only one element.
X.sum()

tensor(66.)

<p style="font-family:ComicSansMS; font-size: 24px; color: orange"> 2.1.4. Broadcasting</p>

In [26]:
#  Broadcasting works according to the following two-step procedure: 
#       (i) expand one or both arrays by copying elements along axes with length 1 
#               so that after this transformation, the two tensors have the same shape; 
#                       (ii) perform an elementwise operation on the resulting arrays.
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [27]:
#  Broadcasting produces a larger 
#       matrix by replicating matrix a along the columns and matrix b along the rows
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

<p style="font-family:ComicSansMS; font-size: 24px; color: orange"> 2.1.5. Saving Memory</p>

In [28]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [29]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1664426997744
id(Z): 1664426997744


In [31]:
# If the value of X is not reused in subsequent computations, 
#       we can also use X[:] = X + Y or X += Y to reduce the memory overhead of the operation.
before = id(X)
X += Y
id(X) == before

True

<p style="font-family:ComicSansMS; font-size: 24px; color: orange"> 2.1.6. Conversion to Other Python Objects</p>

In [32]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [34]:
# To convert a size-1 tensor to a Python scalar, 
#       we can invoke the item function or Python’s built-in functions.
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

<p style="font-family:ComicSansMS; font-size: 24px; color: orange"> 2.1.8. Exercises</p>

In [41]:
X = torch.arange(12, dtype=torch.float32).reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [39]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [42]:
# 1. Run the code in this section. 
# Change the conditional statement X == Y to X < Y or X > Y, and then see what kind of tensor you can get.
x,y,x == y,x < y,x > y

(tensor([1., 2., 4., 8.]),
 tensor([2, 2, 2, 2]),
 tensor([False,  True, False, False]),
 tensor([ True, False, False, False]),
 tensor([False, False,  True,  True]))

In [52]:
# 2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g.,
# 3-dimensional tensors. 
a = torch.arange(3).reshape((3, 1))
b = torch.arange(6).reshape((1, 2, 3))
a.shape, b.shape
# Is the result the same as expected?

(torch.Size([3, 1]), torch.Size([1, 2, 3]))

In [53]:
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [54]:
b + a

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1