In [1]:
import torch
print(torch.__version__) 

2.7.0+cpu


<p style="font-family:ComicSansMS; font-size: 30px; color: magenta"> 2.5. Automatic Differentiation</p>

<p style="font-family:ComicSansMS; font-size: 24px; color: orange"> 2.5.1. A Simple Function</p>

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
# Before we calculate the gradient of y with respect to x, we need a place to store it.
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad  # The gradient is None by default

In [4]:
# We now calculate our function of x and assign the result to y.
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
# We can now take the gradient of y with respect to x by calling its backward method.
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
# We can now verify that the automatic gradient computation and the expected result are identical.
x.grad == 4 * x

tensor([True, True, True, True])

In [7]:
# To reset the gradient buffer, we can call x.grad.zero_() as follows:
x.grad.zero_()  # Reset the gradient
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

<p style="font-family:ComicSansMS; font-size: 24px; color: orange"> 2.5.2. Backward for Non-Scalar Variables</p>

In [8]:
x.grad.zero_()
y = x * x
y.backward(gradient=torch.ones(len(y)))  # Faster: y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

<p style="font-family:ComicSansMS; font-size: 24px; color: orange"> 2.5.3. Detaching Computation</p>

In [9]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [10]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

<p style="font-family:ComicSansMS; font-size: 24px; color: orange"> 2.5.4. Gradients and Python Control Flow</p>

In [11]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [12]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [13]:
a.grad == d / a

tensor(True)